### ISSUE TITLE
Deployment Pipeline

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-53#21]
```[tasklist]
### Tasks
- [x] I can play the game on the web
- [x] I can play the game on Windows
- [x] I can play the game on Linux
```
