### ISSUE TITLE
🏆 Enemies

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-53#3]
```[tasklist]
### Tasks
- [x] White blood cells static on vessel walls
- [x] Plaque
- [x] Floating Red Blood Cells
- [x] Red Blood Cell Bump Effects
```
