### ISSUE TITLE
🏆Stats Tracking

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-53#5]
```[tasklist]
### Tasks
- [x] https://github.com/astro-panda/ldjam-53/issues/68
- [ ] https://github.com/astro-panda/ldjam-53/issues/60
- [ ] https://github.com/astro-panda/ldjam-53/issues/61
```
