### ISSUE TITLE
Win Screen

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-53#71]
When I win the game

```[tasklist]
### Tasks
- [x] There is a screen that tells me I won
- [x] There is a readout of all the enemies and colonies I destroyed
- [x] There is a readout of how long it took to win
```
